mutation commitDocumentAttributes($details: _UpdatePdsContractInput!, $detailsCompare: _ComparePdsContractInput!, $document: _UpdateDocumentInput!, $compare: _CompareDocumentInput!, $version: _CreateDocumentVersionInput!, $previous: _UpdateDocumentVersionInput!, $command: _CreateDocumentCommandInput!) { packet { updateDocument(input: $document, compare: $compare) { id } updatePdsContract(input: $details, compare: $detailsCompare) { id } createDocumentVersion(input: $version) { id } updateDocumentVersion(input: $previous) { id } createDocumentCommand(input: $command) { id } } }
